#################################################################
# +-----------------------------------------------------------+ #
# |                     Setup Data Manager                    | #
# |                        By Michele                         | #
# +-----------------------------------------------------------+ #
#################################################################

#################################################################
# ----------------------- Donations <3 ------------------------ #
# ---------------- https://ko-fi.com/MikesLab ----------------- #
#################################################################

#################################################################
# ------------------------ Source Code ------------------------ #
# ------ https://github.com/MichealAPI/SetupDataManager ------- #
#################################################################

mongo-uri: YOUR_MONGO_URI
database: YOUR_DATABASE_NAME
licenses-collection: licenses
files-collection: files